package main

import (
	"github.com/amazon-simple-workflow-service/mcp-server/config"
	"github.com/amazon-simple-workflow-service/mcp-server/models"
	tools_x_amz_target_simpleworkflowservice_pollfordecisiontask "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_pollfordecisiontask"
	tools_x_amz_target_simpleworkflowservice_registerworkflowtype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_registerworkflowtype"
	tools_x_amz_target_simpleworkflowservice_countpendingactivitytasks "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_countpendingactivitytasks"
	tools_x_amz_target_simpleworkflowservice_pollforactivitytask "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_pollforactivitytask"
	tools_x_amz_target_simpleworkflowservice_describedomain "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_describedomain"
	tools_x_amz_target_simpleworkflowservice_respondactivitytaskcompleted "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_respondactivitytaskcompleted"
	tools_x_amz_target_simpleworkflowservice_deprecatedomain "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_deprecatedomain"
	tools_x_amz_target_simpleworkflowservice_undeprecatedomain "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_undeprecatedomain"
	tools_x_amz_target_simpleworkflowservice_countopenworkflowexecutions "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_countopenworkflowexecutions"
	tools_x_amz_target_simpleworkflowservice_recordactivitytaskheartbeat "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_recordactivitytaskheartbeat"
	tools_x_amz_target_simpleworkflowservice_undeprecateactivitytype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_undeprecateactivitytype"
	tools_x_amz_target_simpleworkflowservice_describeworkflowexecution "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_describeworkflowexecution"
	tools_x_amz_target_simpleworkflowservice_listactivitytypes "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_listactivitytypes"
	tools_x_amz_target_simpleworkflowservice_listtagsforresource "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_listtagsforresource"
	tools_x_amz_target_simpleworkflowservice_signalworkflowexecution "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_signalworkflowexecution"
	tools_x_amz_target_simpleworkflowservice_countpendingdecisiontasks "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_countpendingdecisiontasks"
	tools_x_amz_target_simpleworkflowservice_describeactivitytype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_describeactivitytype"
	tools_x_amz_target_simpleworkflowservice_tagresource "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_tagresource"
	tools_x_amz_target_simpleworkflowservice_listworkflowtypes "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_listworkflowtypes"
	tools_x_amz_target_simpleworkflowservice_respondactivitytaskcanceled "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_respondactivitytaskcanceled"
	tools_x_amz_target_simpleworkflowservice_listclosedworkflowexecutions "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_listclosedworkflowexecutions"
	tools_x_amz_target_simpleworkflowservice_responddecisiontaskcompleted "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_responddecisiontaskcompleted"
	tools_x_amz_target_simpleworkflowservice_listopenworkflowexecutions "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_listopenworkflowexecutions"
	tools_x_amz_target_simpleworkflowservice_terminateworkflowexecution "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_terminateworkflowexecution"
	tools_x_amz_target_simpleworkflowservice_undeprecateworkflowtype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_undeprecateworkflowtype"
	tools_x_amz_target_simpleworkflowservice_getworkflowexecutionhistory "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_getworkflowexecutionhistory"
	tools_x_amz_target_simpleworkflowservice_countclosedworkflowexecutions "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_countclosedworkflowexecutions"
	tools_x_amz_target_simpleworkflowservice_describeworkflowtype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_describeworkflowtype"
	tools_x_amz_target_simpleworkflowservice_respondactivitytaskfailed "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_respondactivitytaskfailed"
	tools_x_amz_target_simpleworkflowservice_registeractivitytype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_registeractivitytype"
	tools_x_amz_target_simpleworkflowservice_deprecateactivitytype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_deprecateactivitytype"
	tools_x_amz_target_simpleworkflowservice_requestcancelworkflowexecution "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_requestcancelworkflowexecution"
	tools_x_amz_target_simpleworkflowservice_registerdomain "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_registerdomain"
	tools_x_amz_target_simpleworkflowservice_untagresource "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_untagresource"
	tools_x_amz_target_simpleworkflowservice_listdomains "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_listdomains"
	tools_x_amz_target_simpleworkflowservice_startworkflowexecution "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_startworkflowexecution"
	tools_x_amz_target_simpleworkflowservice_deprecateworkflowtype "github.com/amazon-simple-workflow-service/mcp-server/tools/x_amz_target_simpleworkflowservice_deprecateworkflowtype"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_simpleworkflowservice_pollfordecisiontask.CreatePollfordecisiontaskTool(cfg),
		tools_x_amz_target_simpleworkflowservice_registerworkflowtype.CreateRegisterworkflowtypeTool(cfg),
		tools_x_amz_target_simpleworkflowservice_countpendingactivitytasks.CreateCountpendingactivitytasksTool(cfg),
		tools_x_amz_target_simpleworkflowservice_pollforactivitytask.CreatePollforactivitytaskTool(cfg),
		tools_x_amz_target_simpleworkflowservice_describedomain.CreateDescribedomainTool(cfg),
		tools_x_amz_target_simpleworkflowservice_respondactivitytaskcompleted.CreateRespondactivitytaskcompletedTool(cfg),
		tools_x_amz_target_simpleworkflowservice_deprecatedomain.CreateDeprecatedomainTool(cfg),
		tools_x_amz_target_simpleworkflowservice_undeprecatedomain.CreateUndeprecatedomainTool(cfg),
		tools_x_amz_target_simpleworkflowservice_countopenworkflowexecutions.CreateCountopenworkflowexecutionsTool(cfg),
		tools_x_amz_target_simpleworkflowservice_recordactivitytaskheartbeat.CreateRecordactivitytaskheartbeatTool(cfg),
		tools_x_amz_target_simpleworkflowservice_undeprecateactivitytype.CreateUndeprecateactivitytypeTool(cfg),
		tools_x_amz_target_simpleworkflowservice_describeworkflowexecution.CreateDescribeworkflowexecutionTool(cfg),
		tools_x_amz_target_simpleworkflowservice_listactivitytypes.CreateListactivitytypesTool(cfg),
		tools_x_amz_target_simpleworkflowservice_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_simpleworkflowservice_signalworkflowexecution.CreateSignalworkflowexecutionTool(cfg),
		tools_x_amz_target_simpleworkflowservice_countpendingdecisiontasks.CreateCountpendingdecisiontasksTool(cfg),
		tools_x_amz_target_simpleworkflowservice_describeactivitytype.CreateDescribeactivitytypeTool(cfg),
		tools_x_amz_target_simpleworkflowservice_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_simpleworkflowservice_listworkflowtypes.CreateListworkflowtypesTool(cfg),
		tools_x_amz_target_simpleworkflowservice_respondactivitytaskcanceled.CreateRespondactivitytaskcanceledTool(cfg),
		tools_x_amz_target_simpleworkflowservice_listclosedworkflowexecutions.CreateListclosedworkflowexecutionsTool(cfg),
		tools_x_amz_target_simpleworkflowservice_responddecisiontaskcompleted.CreateResponddecisiontaskcompletedTool(cfg),
		tools_x_amz_target_simpleworkflowservice_listopenworkflowexecutions.CreateListopenworkflowexecutionsTool(cfg),
		tools_x_amz_target_simpleworkflowservice_terminateworkflowexecution.CreateTerminateworkflowexecutionTool(cfg),
		tools_x_amz_target_simpleworkflowservice_undeprecateworkflowtype.CreateUndeprecateworkflowtypeTool(cfg),
		tools_x_amz_target_simpleworkflowservice_getworkflowexecutionhistory.CreateGetworkflowexecutionhistoryTool(cfg),
		tools_x_amz_target_simpleworkflowservice_countclosedworkflowexecutions.CreateCountclosedworkflowexecutionsTool(cfg),
		tools_x_amz_target_simpleworkflowservice_describeworkflowtype.CreateDescribeworkflowtypeTool(cfg),
		tools_x_amz_target_simpleworkflowservice_respondactivitytaskfailed.CreateRespondactivitytaskfailedTool(cfg),
		tools_x_amz_target_simpleworkflowservice_registeractivitytype.CreateRegisteractivitytypeTool(cfg),
		tools_x_amz_target_simpleworkflowservice_deprecateactivitytype.CreateDeprecateactivitytypeTool(cfg),
		tools_x_amz_target_simpleworkflowservice_requestcancelworkflowexecution.CreateRequestcancelworkflowexecutionTool(cfg),
		tools_x_amz_target_simpleworkflowservice_registerdomain.CreateRegisterdomainTool(cfg),
		tools_x_amz_target_simpleworkflowservice_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_simpleworkflowservice_listdomains.CreateListdomainsTool(cfg),
		tools_x_amz_target_simpleworkflowservice_startworkflowexecution.CreateStartworkflowexecutionTool(cfg),
		tools_x_amz_target_simpleworkflowservice_deprecateworkflowtype.CreateDeprecateworkflowtypeTool(cfg),
	}
}
